/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import javax.swing.JTabbedPane;

/**
 *
 * @author Kiennguyen
 */
public class KhuyenMaiMainPanel extends javax.swing.JPanel {

     private KhuyenMaiPanel panelHoaDon;
    private KhuyenMaiDvuPanel panelDichVu;
    
    public KhuyenMaiMainPanel(int userId, String username) {
        initComponents();
        setLayout(new BorderLayout());

        // Tạo tabbed pane
        JTabbedPane tabbedPane = new JTabbedPane();

        // Tạo 2 tab
        KhuyenMaiPanel panelHoaDon = new KhuyenMaiPanel(userId, username);
        KhuyenMaiDvuPanel panelDichVu = new KhuyenMaiDvuPanel(userId, username);

        // Thêm tab vào tabbedPane
        tabbedPane.addTab("Khuyến mãi hóa đơn", panelHoaDon);
        tabbedPane.addTab("Khuyến mãi dịch vụ", panelDichVu);

        // Thêm tab vào panel chính
        add(tabbedPane, BorderLayout.CENTER);
    }
    
    
    public KhuyenMaiPanel getPanelHoaDonKM() {
        return panelHoaDon;
    }

    public KhuyenMaiDvuPanel getPanelDichVuKM() {
        return panelDichVu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
