/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import GUI.LoaiHangPanel;
import GUI.NhaCungCapPanel;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Kiennguyen
 */
public class ThietLapPanel extends javax.swing.JPanel {
    
    private CardLayout cardLayout;
    private JPanel contentPanel;
    
    public ThietLapPanel() {
        initComponents();

        setLayout(new BorderLayout());

        // === TOP PANEL chứa tiêu đề + nút ===
        JPanel topPanel = new JPanel(new BorderLayout());
        topPanel.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));

        // Tiêu đề
        JLabel lblTitle = new JLabel("Thiết Lập");
        lblTitle.setFont(new Font("Arial", Font.BOLD, 24));
        lblTitle.setForeground(new Color(0, 128, 128)); // Xanh đậm
        topPanel.add(lblTitle, BorderLayout.WEST);

        // Nút chọn
        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 20, 0)); // căn phải, cách nhau 20px

        JButton btnNhaCungCap = new JButton("Nhà Cung Cấp");
        JButton btnLoaiHang = new JButton("Loại Dịch Vụ");

        // Styling nút
        styleBigGreenButton(btnNhaCungCap);
        styleBigGreenButton(btnLoaiHang);

        buttonPanel.add(btnNhaCungCap);
        buttonPanel.add(btnLoaiHang);
        topPanel.add(buttonPanel, BorderLayout.EAST);

        add(topPanel, BorderLayout.NORTH);

        // === PHẦN NỘI DUNG ===
        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);
        contentPanel.add(new NhaCungCapPanel(), "ncc");
        contentPanel.add(new LoaiHangPanel(), "loai");

        add(contentPanel, BorderLayout.CENTER);

        // === Sự kiện nút ===
        btnNhaCungCap.addActionListener(e -> cardLayout.show(contentPanel, "ncc"));
        btnLoaiHang.addActionListener(e -> cardLayout.show(contentPanel, "loai"));
    }


    private void styleBigGreenButton(JButton button) {
        button.setBackground(new Color(0, 128, 128));
        button.setForeground(Color.WHITE);
        button.setFont(new Font("Arial", Font.BOLD, 16));
        button.setPreferredSize(new Dimension(160, 40));
        button.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
