/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DTO.Session;
import javax.swing.*;
import java.awt.*;
import java.net.URL;

public class TopBarPanel extends javax.swing.JPanel {

    /**
     * Creates new form TopBarPanel
     */
  public TopBarPanel() {
        initComponents();
        setBackground(new Color(244, 67, 54)); // đỏ
        setLayout(new BorderLayout());
        setPreferredSize(new Dimension(getWidth(), 50));

        // ===== Logo bên trái với icon =====
        ImageIcon logoIcon = loadIcon("Icon/icons8_menu_48px_1.png", 24, 24);
        JLabel logo = new JLabel("  Unique Developer", logoIcon, JLabel.LEFT);
        logo.setFont(new Font("Segoe UI", Font.BOLD, 18));
        logo.setForeground(Color.WHITE);

        // ===== Panel bên phải chứa các icon =====
        JPanel rightPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 20, 10));
        rightPanel.setOpaque(false);

        // Thêm các icon
//        rightPanel.add(new JLabel(loadIcon("Icon/search_26px.png", 20, 20)));
//        rightPanel.add(new JLabel(loadIcon("Icon/group_message_26px.png", 20, 20)));
//        rightPanel.add(new JLabel(loadIcon("Icon/bell_26px.png", 20, 20)));

        // ===== Avatar + text =====
         String roleLabel = "Admin";
    if (Session.vaiTro != null && Session.vaiTro.equalsIgnoreCase("employee")) {
        roleLabel = "Nhân Viên";
    }

    JLabel userLabel = new JLabel(" Hello, " + roleLabel);
    userLabel.setIcon(loadIcon("Icon/male_user_50px.png", 26, 26));
    userLabel.setForeground(Color.WHITE);
    userLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
    rightPanel.add(userLabel);

        // ===== Thêm thành phần vào TopBar =====
        add(logo, BorderLayout.WEST);
        add(rightPanel, BorderLayout.EAST);
    }

    // ===== Hàm hỗ trợ load và resize icon từ resource =====
    private ImageIcon loadIcon(String path, int width, int height) {
        URL iconURL = getClass().getResource("/" + path);
        if (iconURL != null) {
            ImageIcon rawIcon = new ImageIcon(iconURL);
            Image scaled = rawIcon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
            return new ImageIcon(scaled);
        } else {
            System.err.println("⚠ Không tìm thấy icon: " + path);
            return null;
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
